import type { Curso } from "@/lib/recommendation";

// Seed temporário para alimentar o banco e os testes enquanto não existe ingestão
// de fontes oficiais. 11 dos 16 cursos são de Administração: esta amostra é
// ilustrativa, não representativa.
export const CURSOS_SEED: Curso[] = [
  {
    id: "fgv-adm",
    curso: "Administração",
    instituicao: "FGV EAESP",
    cidade: "São Paulo",
    estado: "SP",
    tipo: "privada",
    modalidade: "presencial",
    duracaoSemestres: 8,
    turnos: ["matutino"],
    ingresso: ["vestibular_proprio"],
    notaCorte: 850,
    mensalidade: { min: 9800, max: 9800 },
    bolsas: true,
    custoVidaCidade: "alto",
    notaMEC: 5,
    taxaEvasao: 4,
    situacaoMEC: "regular",
  },
  {
    id: "insper-adm",
    curso: "Administração",
    instituicao: "Insper",
    cidade: "São Paulo",
    estado: "SP",
    tipo: "privada",
    modalidade: "presencial",
    duracaoSemestres: 8,
    turnos: ["matutino", "integral"],
    ingresso: ["vestibular_proprio"],
    notaCorte: 800,
    mensalidade: { min: 9200, max: 9200 },
    bolsas: true,
    custoVidaCidade: "alto",
    notaMEC: 5,
    taxaEvasao: 6,
    situacaoMEC: "regular",
  },
  {
    id: "mackenzie-adm",
    curso: "Administração",
    instituicao: "Mackenzie",
    cidade: "São Paulo",
    estado: "SP",
    tipo: "privada",
    modalidade: "presencial",
    duracaoSemestres: 8,
    turnos: ["matutino", "noturno"],
    ingresso: ["sisu", "enem_direto", "vestibular_proprio"],
    notaCorte: 650,
    mensalidade: { min: 2400, max: 2400 },
    bolsas: true,
    custoVidaCidade: "alto",
    notaMEC: 4,
    taxaEvasao: 12,
    situacaoMEC: "regular",
  },
  {
    id: "usp-fea-adm",
    curso: "Administração",
    instituicao: "USP - FEA",
    cidade: "São Paulo",
    estado: "SP",
    tipo: "publica",
    modalidade: "presencial",
    duracaoSemestres: 8,
    turnos: ["matutino", "noturno"],
    ingresso: ["sisu"],
    notaCorte: 780,
    mensalidade: { min: 0, max: 0 },
    bolsas: true,
    custoVidaCidade: "alto",
    notaMEC: 5,
    taxaEvasao: 5,
    situacaoMEC: "regular",
  },
  {
    id: "pucsp-adm",
    curso: "Administração",
    instituicao: "PUC-SP",
    cidade: "São Paulo",
    estado: "SP",
    tipo: "privada",
    modalidade: "presencial",
    duracaoSemestres: 8,
    turnos: ["noturno"],
    ingresso: ["vestibular_proprio", "sisu"],
    notaCorte: 620,
    mensalidade: { min: 1900, max: 1900 },
    bolsas: true,
    custoVidaCidade: "alto",
    notaMEC: 4,
    taxaEvasao: 15,
    situacaoMEC: "regular",
  },
  {
    id: "unip-adm",
    curso: "Administração",
    instituicao: "UNIP",
    cidade: "São Paulo",
    estado: "SP",
    tipo: "privada",
    modalidade: "hibrido",
    duracaoSemestres: 8,
    turnos: ["noturno"],
    ingresso: ["historico", "sisu"],
    notaCorte: 500,
    mensalidade: { min: 700, max: 700 },
    bolsas: true,
    custoVidaCidade: "alto",
    notaMEC: 3,
    taxaEvasao: 22,
    situacaoMEC: "regular",
  },
  {
    id: "ufrj-adm",
    curso: "Administração",
    instituicao: "UFRJ",
    cidade: "Rio de Janeiro",
    estado: "RJ",
    tipo: "publica",
    modalidade: "presencial",
    duracaoSemestres: 8,
    turnos: ["matutino", "vespertino"],
    ingresso: ["sisu"],
    notaCorte: 700,
    mensalidade: { min: 0, max: 0 },
    bolsas: true,
    custoVidaCidade: "medio",
    notaMEC: 4,
    taxaEvasao: 10,
    situacaoMEC: "regular",
  },
  {
    id: "ufmg-adm",
    curso: "Administração",
    instituicao: "UFMG",
    cidade: "Belo Horizonte",
    estado: "MG",
    tipo: "publica",
    modalidade: "presencial",
    duracaoSemestres: 8,
    turnos: ["matutino"],
    ingresso: ["sisu"],
    notaCorte: 690,
    mensalidade: { min: 0, max: 0 },
    bolsas: true,
    custoVidaCidade: "medio",
    notaMEC: 4,
    taxaEvasao: 9,
    situacaoMEC: "regular",
  },
  {
    id: "ufsc-adm",
    curso: "Administração",
    instituicao: "UFSC",
    cidade: "Florianópolis",
    estado: "SC",
    tipo: "publica",
    modalidade: "presencial",
    duracaoSemestres: 8,
    turnos: ["vespertino", "noturno"],
    ingresso: ["sisu"],
    notaCorte: 660,
    mensalidade: { min: 0, max: 0 },
    bolsas: true,
    custoVidaCidade: "medio",
    notaMEC: 4,
    taxaEvasao: 8,
    situacaoMEC: "regular",
  },
  {
    id: "faap-adm",
    curso: "Administração",
    instituicao: "FAAP",
    cidade: "São Paulo",
    estado: "SP",
    tipo: "privada",
    modalidade: "presencial",
    duracaoSemestres: 8,
    turnos: ["matutino", "noturno"],
    ingresso: ["vestibular_proprio"],
    notaCorte: 700,
    mensalidade: { min: 3600, max: 3600 },
    bolsas: true,
    custoVidaCidade: "alto",
    notaMEC: 4,
    taxaEvasao: 11,
    situacaoMEC: "regular",
  },
  {
    id: "estacio-adm",
    curso: "Administração",
    instituicao: "Estácio",
    cidade: "São Paulo",
    estado: "SP",
    tipo: "privada",
    modalidade: "EAD",
    duracaoSemestres: 8,
    turnos: ["EAD"],
    ingresso: ["historico"],
    notaCorte: 450,
    mensalidade: { min: 400, max: 400 },
    bolsas: true,
    custoVidaCidade: "alto",
    notaMEC: 3,
    taxaEvasao: 28,
    situacaoMEC: "regular",
  },
  {
    id: "usp-poli-prod",
    curso: "Engenharia de Produção",
    instituicao: "USP - Poli",
    cidade: "São Paulo",
    estado: "SP",
    tipo: "publica",
    modalidade: "presencial",
    duracaoSemestres: 10,
    turnos: ["integral"],
    ingresso: ["sisu"],
    notaCorte: 830,
    mensalidade: { min: 0, max: 0 },
    bolsas: true,
    custoVidaCidade: "alto",
    notaMEC: 5,
    taxaEvasao: 7,
    situacaoMEC: "regular",
  },
  {
    id: "usp-direito",
    curso: "Direito",
    instituicao: "USP",
    cidade: "São Paulo",
    estado: "SP",
    tipo: "publica",
    modalidade: "presencial",
    duracaoSemestres: 10,
    turnos: ["matutino"],
    ingresso: ["sisu"],
    notaCorte: 850,
    mensalidade: { min: 0, max: 0 },
    bolsas: true,
    custoVidaCidade: "alto",
    notaMEC: 5,
    taxaEvasao: 3,
    situacaoMEC: "regular",
  },
  {
    id: "unicamp-cc",
    curso: "Ciência da Computação",
    instituicao: "Unicamp",
    cidade: "Campinas",
    estado: "SP",
    tipo: "publica",
    modalidade: "presencial",
    duracaoSemestres: 8,
    turnos: ["integral"],
    ingresso: ["sisu"],
    notaCorte: 800,
    mensalidade: { min: 0, max: 0 },
    bolsas: true,
    custoVidaCidade: "medio",
    notaMEC: 5,
    taxaEvasao: 15,
    situacaoMEC: "regular",
  },
  {
    id: "usp-medicina",
    curso: "Medicina",
    instituicao: "USP",
    cidade: "São Paulo",
    estado: "SP",
    tipo: "publica",
    modalidade: "presencial",
    duracaoSemestres: 12,
    turnos: ["integral"],
    ingresso: ["sisu"],
    notaCorte: 920,
    mensalidade: { min: 0, max: 0 },
    bolsas: true,
    custoVidaCidade: "alto",
    notaMEC: 5,
    taxaEvasao: 1,
    situacaoMEC: "regular",
  },
  {
    id: "belasartes-design",
    curso: "Design",
    instituicao: "Belas Artes",
    cidade: "São Paulo",
    estado: "SP",
    tipo: "privada",
    modalidade: "presencial",
    duracaoSemestres: 8,
    turnos: ["noturno"],
    ingresso: ["vestibular_proprio"],
    notaCorte: 550,
    mensalidade: { min: 1800, max: 1800 },
    bolsas: true,
    custoVidaCidade: "alto",
    notaMEC: 4,
    taxaEvasao: 18,
    situacaoMEC: "regular",
  },
];
